Grafica
kaitakami/indicadores-economicos pull request #10
Opened 2023-03-30 20:10 UTC by PatoKuack

Aprendí a crear Draft Pull Request ;P

2023-04-01 01:19 UTC, PatoKuack commented
¡Kai! Ya coloqué los selects, pero tengo un problema actualizando el título de la gráfica, crees q le puedas echar un vistazo para ver ¿por qué la actualización del título va atrasada una recarga? =S

2023-04-01 01:52 UTC, kaitakami commented
También ya actualicé useFetchTicker para que te retorne los valores de manera organizada para que los puedas utilizar con Tremor :sparkles: 
Si puedes checar eso antes de hacer los cambios, mientras yo checo lo del título

2023-04-01 02:24 UTC, kaitakami commented
@PatoKuack la razón por la que el título no cambia es porque el state `currentDataTicker` no se actualiza cada vez que el select cambía de país. Esto es porque la función que le pasas al onChange no está cambiando el país. Lo que yo haría sería hacer lo que estás haciendo solo que en vez de crear un nuevo objeto simplemente haría 
```
// FormGraphicData.jsx
...
const getFormInfo = (event)  =>  {
  ...
  // En React puedes usar el state previo desde el setState function :arrow_down: 
  setCurrentDataTicker((prevState) => ({ // Entre parentesis para hacer un return implicito
    ...prevState, // destructuring del estado
    [event.target.name]: event.target.value // El name ya lo tienes puesto solo lo cambiaría para que sea el mismo al estado 
    setCurrentDataTicker, después le asignas el nuevo value
  }))
}
...
...
```

Un ejemplo de su uso es esta página que cree https://github.com/kaitakami/image-generation/blob/main/app/page.tsx
```
 const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {   // en este caso estoy usando typescript (ignora)
    setGuest({
      ...guest, // Estoy usando guest porque esta en el mismo archivo pero puedes hacer lo que hice arriba (prevGuest) => ({...})
      [event.target.name]: event.target.value // Lo tienes que poner entre parentesis rectangulares
    })
  }
```
También mira el state, las keys, y los inputs para ver como todo está conectado.
Mira la [página](https://fundadores-image-generator.vercel.app/), pon valores y mira como el resultado va cambiando dinámicamente.

2023-04-04 22:59 UTC, PatoKuack commented
Kai! en el archivo App.jsx coloqué un estado que inicia con un objeto con un array vacio para que no marque error por culpa de un _undefined_.
También usé dos useEffects para actualizar los datos al cargar la página y cada que se modificara el formulario:

```
const [dataStats, setDataStats] = useState({ data: [] })

useEffect(() => {
    if (data) {
      setDataStats(data)
    }
  }, [currentDataTicker])

  useEffect(() => {
    if (data) {
      setDataStats(data)
    }
  }, [])
```

En el archivo FormGraphicData coloqué ese estado para ver en la terminal si se actualizaba jeje, pero no tiene una función
```
data: props.dataStats.data,
otro: props.dataStats.description
```

Y en StatsGraphic.jsx imprimo en consola para verificar si estan sincronizados los datos y aparte uso el mismo estado q creé (dataStats) para visualizar las estadisticas:
```
useEffect(() => {
    console.log('--------------------')
    // console.log(props.dataStats)
    console.log(props.currentDataTicker)
  }, [props.currentDataTicker])

...

<LineChart
        className="mt-4 h-80 text-textBody"
        data={props.dataStats.data}
        index="date"
        categories={['value']}
        colors={['lime']}
        valueFormatter={valueFormatter}
        showLegend={false}
        yAxisWidth={48}
      />
```

2023-04-05 12:42 UTC, kaitakami commented
Había instalado eslint de la manera incorrecta! Una disculpa, ya lo solucioné, antes de hacer un commit corre prettier y eslint.

2023-04-05 13:10 UTC, kaitakami requested changes
También estaré trabajando en está branch! Por cierto, se recomienda que por branch el número de líneas cambiadas sea menos de 150 usualmente, está vez nos pasamos casi el doble pero de ahora hacía adelante hay que hacer cambios más pequeños pero listos para producción :)

2023-04-05 13:10 UTC, kaitakami commented on src/App.jsx
> +  })
De preferencia el initial state debería de ser null o un objeto sin valores, al ser vacío se debería de mostrar un mensaje como: "Inicia seleccionando un país y un indíce"

2023-04-05 13:10 UTC, kaitakami commented on src/components/StatsGraphic.jsx
> +          {!!props.error && props.onError()}
`{props.error && <span>...</span>}`

2023-04-05 13:10 UTC, kaitakami commented on src/components/StatsGraphic.jsx
> +          {(!props.loading && !props.error) && props.render()}
Mejor poner el contenido que hay por dentro para disminuir la complejidad, al poner solo `render()` que es lo que esta renderizando y no hay punto para saber en donde se pasa la prop al menos que se busque.

2023-04-05 13:10 UTC, kaitakami commented on src/hooks/useOrderIndicesList.js
Entiendo que este custom hook ordena los indices, sin embargo, cuál es la funcionalidad?

2023-04-06 02:21 UTC, PatoKuack commented on public/coin.svg
aaaa okas okas jeje XD
también recordé q tenemos el tostador, y mejor lo usaré =P

2023-04-07 21:57 UTC, PatoKuack commented on src/components/FormGraphicData.jsx
> +        ref={formGetData}
Mi amigable amigo Kai, el ref es un hook de react que permite obtener el dato actual de cualquiera de los inputs de un formulario. Es muy útil para evitar lios con el render y la actualización de estados XD

2023-04-07 22:17 UTC, PatoKuack commented on src/hooks/useOrderIndicesList.js
Es para que los países y las descripciones de los índices de las tablas salgan en orden alfabetico y si buscan al querido México, lo encuentren más facilmente en el rango de las "M".

2023-04-07 22:23 UTC, PatoKuack commented on src/App.jsx
> +          render={() => <span>{currentDataTicker.register} of {currentDataTicker.country}</span>}
XD jajaja es que lo primero que se ve al darle mantenimiento a un código de react, es el archivo App y si se muestran las acciones de los componentes resulta más fácil entender la componsición de todo sin tener que ir a cada componente a  visualizar su fincionamiento, esa el la razón de q lo hiciera así, aunque supongo q no es degran relevancia porque solo renderiza un string XD jaja, d todos modos ya lo modifiqué usando la tostadora.

2023-04-11 09:08 UTC, kaitakami requested changes
Hice 4 comentarios y solo es para remover archivos no usados menos uno.
Antes de hacer el merge, hay un error cuando la aplicación se corre en local
```
Warning: Cannot update a component (`Ie`) while rendering a different component (`StatsGraphic`). To locate the bad setState() call inside `StatsGraphic`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at StatsGraphic (http://localhost:5173/src/components/StatsGraphic.jsx:23:3)
    at section
    at div
    at div
    at Layout (http://localhost:5173/src/components/Layout.jsx:19:3)
    at App (http://localhost:5173/src/App.jsx:26:53)
```

2023-04-11 09:08 UTC, kaitakami commented on src/hooks/useOrderIndicesList.js
Este custom hook no esta siendo utilizado

2023-04-11 09:08 UTC, kaitakami commented on vite.config.js.timestamp-1680910475082.mjs
Este archivo es innecesario

2023-04-11 19:39 UTC, PatoKuack commented on src/App.jsx
> +					)}
aaaaa, poes lo hacía así porque he estado aprendiendo react de esa manera, =P pero no tengo problema con modificar la forma de trabajar. Tienes unos puntos muy buenos y _estoy de acuerdo en eliminar esa render function_ =B
yyyy vale! jajaja gracias por decirme todo lo q dices, xD no sabía q se t escondian los comentarios que no habías visto cuando los resolvía =S

2023-04-11 19:45 UTC, PatoKuack commented on vite.config.js.timestamp-1680910475082.mjs
Perdón, se creó solito O.O y no m di cuenta

2023-04-11 21:40 UTC, PatoKuack commented
listo! se corrigió todo lo que pedisteis. Checa si esta bien la modificación de la render prop
aaaaa bueno, lo querías cambiar después O.O jeje, lo modifiqué antes d acabar de leer bien tu mensaje, =S pero quedó bien sin alterar el código XD

2023-04-12 13:00 UTC, kaitakami approved these changes
Listo! Hacer el merge después de hacer 19 commits, 2 semanas, gracias y felicidades!

2023-04-12 13:05 UTC, merged