Crea componente footer
kaitakami/indicadores-economicos pull request #7
Opened 2023-03-27 01:31 UTC by kaitakami

Esto es un draft. Qué te parece el footer? Te gusta el diseño? Qué le cambiarías?
Una vez estemos conformes con el footer haré la PR.

2023-03-27 01:37 UTC, kaitakami commented
Puedes ver el bot viendo el link del deploy preview que el bot de netlify comentó ✨

2023-03-27 02:42 UTC, PatoKuack requested changes
esta genial que aparescan los perfiles de GitHub =D

- creo que primero debería ir el logo de **Git**, después los **perfiles** y luego el **texto**

2023-03-27 02:46 UTC, kaitakami commented
Como se lee de izquierda a derecha siento que el texto se vería raro estando al final. Lo podemos poner en medio o en la izquierda. El logo de github en la izquierda y los perfiles en la derecha.

2023-03-27 03:38 UTC, PatoKuack commented
Aaaaa pues hagámoslo como el d esta página que esta el logo de GitHub y el texto juntos con una separación de 8px y al final irían los perfiles.
**Logo ©Texto** _______________ **Perfiles**

2023-03-29 00:48 UTC, PatoKuack approved these changes
Bien bien =B

2023-03-29 00:48 UTC, merged