Grafica
kaitakami/indicadores-economicos pull request #8
Opened 2023-03-28 01:30 UTC by PatoKuack

Me falta conectar los datos con la gráfica de forma dinámica

al dar clic en un botón se actualiza el string de **currentTicker** y se pide al hook que busque los datos del código que se le pide:

`const [currentTicker, setCurrentTicker] = useState("US");`

`const geographyOptions = [`
`    { name: "EEUU", code: "US" },`
`    { name: "India", code: "IN" },`
`    { name: "México", code: "MX" },`
`];`

`const {`
`    data,`
`    loading,`
`    error,`
`    handleCancelRequest`
`} = useFetchTicker(`CPI${currentTicker}`);`

2023-03-28 04:19 UTC, kaitakami requested changes
La aplicación está dando un error en producción.
```
Uncaught TypeError: Cannot read properties of null (reading 'data')
```

2023-03-28 04:19 UTC, kaitakami commented on src/App.jsx
> +  const geographyOptions = [
Está información la puedes importar desde
`./src/utils/indices.js`
Filtra el array de objetos para que te retorne los países sin repetir.

2023-03-28 04:19 UTC, kaitakami commented on src/App.jsx
> +  const [currentTicker, setCurrentTicker] = useState("US");
Los tickers no son países, puedes revisar indices.js para más información.
```
 {
    "ticker": "CPIUS",
    "country": "United States",
    "name": "Consumer price index"
  },
```

2023-03-28 04:19 UTC, kaitakami commented on README.md
No te preocupes del readme, lo hacemos cuando acabemos el proyecto

2023-03-28 19:34 UTC, PatoKuack commented on src/App.jsx
> +  const geographyOptions = [
aaaa no ma! =0 no habia visto ese archivo 😅

2023-03-28 19:49 UTC, PatoKuack commented on README.md
vale, solo estoy comentando las referencias de información para tenerlas a la mano y q no se nos olvide alguna al final =P si es q se colocan referencias O.O

2023-03-29 00:38 UTC, PatoKuack commented
Kai!!! ya lo arreglé!!! checalo y dime q t parece ;)

2023-03-29 02:40 UTC, kaitakami requested changes
En general muy buen uso del state y tailwind css. Para haber empezado a usarlo hace tan poco estás haciendo muy buen uso 🙌
Solo vi que hay varios en mejoras en cuanto buenas prácticas

2023-03-29 02:40 UTC, kaitakami commented on src/components/StatsGraphic.jsx
> +const latency = [
Eliminar esto antes de hacer el merge

2023-03-29 02:40 UTC, kaitakami commented on src/components/StatsGraphic.jsx
> +        <Title className="mt-2 text-textBody">Consumer price index of {props.currentCountry}</Title>
Muy buen uso del state!

2023-03-29 02:40 UTC, kaitakami commented on src/components/ItemNavGraphic.jsx
> +  /* useEffect(()=>{
Eliminar este comentario. Solo agregar comentarios que sirven de referencia

2023-03-29 02:40 UTC, kaitakami commented on src/components/ItemNavGraphic.jsx
> +function ItemNavGraphic(props) {
Creo que este componente es innecesario 🤔
Lo podemos poner dentro del mismo archivo del componente en el que se está utilizando

2023-03-29 02:40 UTC, kaitakami commented on src/components/Layout.jsx
> +      <div className="bg-bgBody text-textBody min-w-screen min-h-screen relative">
Queda un poco extraño poner bg-bg y text-text, podemos cambiarlo para que simplemente sea bf-body y text-body

2023-03-29 02:40 UTC, kaitakami commented on src/components/NavGraphic.jsx
> +  /* useEffect(()=>{
Eliminar comentario antes de hacer el merge

2023-03-29 02:40 UTC, kaitakami commented on tailwind.config.cjs
>        backgroundColor: {
En este objeto declaramos explícitamente que es background color por lo que no es necesario ponerle bg a cada key dentro del objeto

2023-03-29 02:40 UTC, kaitakami commented on tailwind.config.cjs
>        textColor: {
Lo mismo con text 😁

2023-03-29 02:40 UTC, kaitakami commented on src/App.jsx
> +  const [currentTicker, setCurrentTicker] = useState("CPIMX");
Buena implementación del state solo que en vez de crear 5 states en este caso es mejor crear un solo state y usar un objeto

2023-03-29 02:40 UTC, kaitakami commented on src/components/ItemNavGraphic.jsx
> +    <li className='flex w-fit px-2 py-1 bg-bgElement rounded-md ring-1 ring-lightColor border-solid cursor-pointer items-center justify-items-center text-center text-sm md:text-base' onClick={() => {
En mobile tiene un height muy alto

2023-03-29 22:21 UTC, PatoKuack commented on src/components/ItemNavGraphic.jsx
> +function ItemNavGraphic(props) {
Aaaaa es que estoy haciendolo con la metodología de Diseño Atómico, o sea dividiendo los componentes en moleculas para formar un organismo.
_Esto puede ayudar a q sean más detectables los errores cuando un componente falla y también se puede limitar las secuelas de un error que se genere en ese item y evitar que llegue a su componente padre. También mejora la escalabilidad de cada componente._
Weno, creo que es útil mantener atomisado esta parte porque funciona con los datos d la API, pero como tú veas Kai, yo confio en tu visión. =o

2023-03-30 00:05 UTC, PatoKuack commented on src/components/ItemNavGraphic.jsx
> +    <li className='flex w-fit px-2 py-1 bg-bgElement rounded-md ring-1 ring-lightColor border-solid cursor-pointer items-center justify-items-center text-center text-sm md:text-base' onClick={() => {
corregido y listirigillo ;)

2023-03-30 00:06 UTC, PatoKuack commented on src/components/StatsGraphic.jsx
> +const latency = [
el array de **latency**? O.o

2023-03-30 00:49 UTC, kaitakami commented on src/components/StatsGraphic.jsx
> +const latency = [
El array de latency ya que no son los datos reales que está retornando la API.

2023-03-30 20:03 UTC, closed without merging